version: "3.8"

services:
  backend:
    image: zayn63/crud-backend
    container_name: crud-backend
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cruddb
    depends_on:
      - mongo

  frontend:
    image: zayn63/crud-frontend
    container_name: crud-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: crud-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
